apiVersion: v1
kind: Pod
metadata:
  name: scheduler
spec:
  containers:
    - name: my-container
      image: docker.io/luoxiao23333/scheduler:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 80
