apiVersion: v1
kind: Service
metadata:
  name: scheduler-svc
  labels: 
    app: scheduler-svc
spec:
  selector:
    app: scheduler
  ports:
  - name: scheduler-port
    port: 8081
    targetPort: 8081
